{
  "info": {
    "name": "Fix Folder"
  }, 
  "Func0": {
    "fields": [
      "just nothing to do with this"
    ], 
    "arguments": [
      "%year% %album%"
    ], 
    "module": "puddlestuff.functions", 
    "func_name": "tag_dir"
  }
}